version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run: mvn clean test
      - run: allure generate allure-results -o allure-report
      - store_artifacts:
          path: target/site/allure-maven-plugin